using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace AuthTestApp.Models
{
    public partial class VicidialCampaign
    {
        [Key]
        public string CampaignId { get; set; }
        public string CampaignName { get; set; }
        public string Active { get; set; }
        public string DialStatusA { get; set; }
        public string DialStatusB { get; set; }
        public string DialStatusC { get; set; }
        public string DialStatusD { get; set; }
        public string DialStatusE { get; set; }
        public string LeadOrder { get; set; }
        public string ParkExt { get; set; }
        public string ParkFileName { get; set; }
        public string WebFormAddress { get; set; }
        public string AllowClosers { get; set; }
        public int HopperLevel { get; set; }
        public string AutoDialLevel { get; set; }
        public string NextAgentCall { get; set; }
        public string LocalCallTime { get; set; }
        public string VoicemailExt { get; set; }
        public int DialTimeout { get; set; }
        public int DialPrefix { get; set; }
        public double CampaignCid { get; set; }
        public int CampaignVdadExten { get; set; }
        public int CampaignRecExten { get; set; }
        public string CampaignRecording { get; set; }
        public string CampaignRecFilename { get; set; }
        public string CampaignScript { get; set; }
        public string GetCallLaunch { get; set; }
        public string AmMessageExten { get; set; }
        public string AmdSendToVmx { get; set; }
        public string XferconfADtmf { get; set; }
        public string XferconfANumber { get; set; }
        public string XferconfBDtmf { get; set; }
        public string XferconfBNumber { get; set; }
        public string AltNumberDialing { get; set; }
        public string ScheduledCallbacks { get; set; }
        public string LeadFilterId { get; set; }
        public int DropCallSeconds { get; set; }
        public string DropAction { get; set; }
        public int SafeHarborExten { get; set; }
        public string DisplayDialableCount { get; set; }
        public string WrapupSeconds { get; set; }
        public string WrapupMessage { get; set; }
        public string CloserCampaigns { get; set; }
        public string UseInternalDnc { get; set; }
        public string AllcallsDelay { get; set; }
        public string OmitPhoneCode { get; set; }
        public string DialMethod { get; set; }
        public string AvailableOnlyRatioTally { get; set; }
        public int AdaptiveDroppedPercentage { get; set; }
        public double AdaptiveMaximumLevel { get; set; }
        public int AdaptiveLatestServerTime { get; set; }
        public string AdaptiveIntensity { get; set; }
        public string AdaptiveDlDiffTarget { get; set; }
        public string ConcurrentTransfers { get; set; }
        public string AutoAltDial { get; set; }
        public string AutoAltDialStatuses { get; set; }
        public string AgentPauseCodesActive { get; set; }
        public string CampaignDescription { get; set; }
        public DateTime CampaignChangedate { get; set; }
        public string CampaignStatsRefresh { get; set; }
        public DateTime CampaignLogindate { get; set; }
        public string DialStatuses { get; set; }
        public string DisableAlterCustdata { get; set; }
        public string NoHopperLeadsLogins { get; set; }
        public string ListOrderMix { get; set; }
        public string CampaignAllowInbound { get; set; }
        public int ManualDialListId { get; set; }
        public string DefaultXferGroup { get; set; }
        public string XferGroups { get; set; }
        public int QueuePriority { get; set; }
        public string DropInboundGroup { get; set; }
        public string QcEnabled { get; set; }
        public string QcStatuses { get; set; }
        public string QcLists { get; set; }
        public string QcShiftId { get; set; }
        public string QcGetRecordLaunch { get; set; }
        public string QcShowRecording { get; set; }
        public string QcWebFormAddress { get; set; }
        public string QcScript { get; set; }
        public string SurveyFirstAudioFile { get; set; }
        public int SurveyDtmfDigits { get; set; }
        public int SurveyNiDigit { get; set; }
        public string SurveyOptInAudioFile { get; set; }
        public string SurveyNiAudioFile { get; set; }
        public string SurveyMethod { get; set; }
        public string SurveyNoResponseAction { get; set; }
        public string SurveyNiStatus { get; set; }
        public string SurveyResponseDigitMap { get; set; }
        public int SurveyXferExten { get; set; }
        public string SurveyCampRecordDir { get; set; }
        public string DisableAlterCustphone { get; set; }
        public string DisplayQueueCount { get; set; }
        public string ManualDialFilter { get; set; }
        public string AgentClipboardCopy { get; set; }
        public string AgentExtendedAltDial { get; set; }
        public string UseCampaignDnc { get; set; }
        public string ThreeWayCallCid { get; set; }
        public string ThreeWayDialPrefix { get; set; }
        public string WebFormTarget { get; set; }
        public string VtigerSearchCategory { get; set; }
        public string VtigerCreateCallRecord { get; set; }
        public string VtigerCreateLeadRecord { get; set; }
        public string VtigerScreenLogin { get; set; }
        public string CpdAmdAction { get; set; }
        public string AgentAllowGroupAlias { get; set; }
        public string DefaultGroupAlias { get; set; }
        public string VtigerSearchDead { get; set; }
        public string VtigerStatusCall { get; set; }
        public string SurveyThirdDigit { get; set; }
        public string SurveyThirdAudioFile { get; set; }
        public string SurveyThirdStatus { get; set; }
        public int SurveyThirdExten { get; set; }
        public string SurveyFourthDigit { get; set; }
        public string SurveyFourthAudioFile { get; set; }
        public string SurveyFourthStatus { get; set; }
        public int SurveyFourthExten { get; set; }
        public string DropLockoutTime { get; set; }
        public string QuickTransferButton { get; set; }
        public string PrepopulateTransferPreset { get; set; }
        public string DropRateGroup { get; set; }
        public string ViewCallsInQueue { get; set; }
        public string ViewCallsInQueueLaunch { get; set; }
        public string GrabCallsInQueue { get; set; }
        public string CallRequeueButton { get; set; }
        public string PauseAfterEachCall { get; set; }
        public string NoHopperDialing { get; set; }
        public string AgentDialOwnerOnly { get; set; }
        public string AgentDisplayDialableLeads { get; set; }
        public string WebFormAddressTwo { get; set; }
        public string WaitforsilenceOptions { get; set; }
        public string AgentSelectTerritories { get; set; }
        public string CampaignCalldate { get; set; }
        public string CrmPopupLogin { get; set; }
        public string CrmLoginAddress { get; set; }
        public string TimerAction { get; set; }
        public string TimerActionMessage { get; set; }
        public string TimerActionSeconds { get; set; }
        public string StartCallUrl { get; set; }
        public string DispoCallUrl { get; set; }
        public string XferconfCNumber { get; set; }
        public string XferconfDNumber { get; set; }
        public string XferconfENumber { get; set; }
        public string UseCustomCid { get; set; }
        public string ScheduledCallbacksAlert { get; set; }
        public string QueuemetricsCallstatusOverride { get; set; }
        public string ExtensionAppendedCidname { get; set; }
        public string ScheduledCallbacksCount { get; set; }
        public string ManualDialOverride { get; set; }
        public string BlindMonitorWarning { get; set; }
        public string BlindMonitorMessage { get; set; }
        public string BlindMonitorFilename { get; set; }
        public string InboundQueueNoDial { get; set; }
        public string TimerActionDestination { get; set; }
        public string EnableXferPresets { get; set; }
        public string HideXferNumberToDial { get; set; }
        public string ManualDialPrefix { get; set; }
        public string Customer3wayHangupLogging { get; set; }
        public int Customer3wayHangupSeconds { get; set; }
        public string Customer3wayHangupAction { get; set; }
        public string IvrParkCall { get; set; }
        public string IvrParkCallAgi { get; set; }
        public string ManualPreviewDial { get; set; }
        public string RealtimeAgentTimeStats { get; set; }
        public string UseAutoHopper { get; set; }
        public string AutoHopperMulti { get; set; }
        public string AutoHopperLevel { get; set; }
        public string AutoTrimHopper { get; set; }
        public string ApiManualDial { get; set; }
        public string ManualDialCallTimeCheck { get; set; }
        public string DisplayLeadsCount { get; set; }
        public string LeadOrderRandomize { get; set; }
        public string LeadOrderSecondary { get; set; }
        public string PerCallNotes { get; set; }
        public string MyCallbackOption { get; set; }
        public string AgentLeadSearch { get; set; }
        public string AgentLeadSearchMethod { get; set; }
        public string QueuemetricsPhoneEnvironment { get; set; }
        public string AutoPausePrecall { get; set; }
        public string AutoPausePrecallCode { get; set; }
        public string AutoResumePrecall { get; set; }
        public string ManualDialCid { get; set; }
        public string PostPhoneTimeDiffAlert { get; set; }
        public string Custom3wayButtonTransfer { get; set; }
        public string AvailableOnlyTallyThreshold { get; set; }
        public string AvailableOnlyTallyThresholdAgents { get; set; }
        public string DialLevelThreshold { get; set; }
        public string DialLevelThresholdAgents { get; set; }
        public string SafeHarborAudio { get; set; }
        public string SafeHarborMenuId { get; set; }
        public string SurveyMenuId { get; set; }
        public string CallbackDaysLimit { get; set; }
        public string DlDiffTargetMethod { get; set; }
        public string DisableDispoScreen { get; set; }
        public string DisableDispoStatus { get; set; }
        public string ScreenLabels { get; set; }
        public string StatusDisplayFields { get; set; }
        public string NaCallUrl { get; set; }
        public string SurveyRecording { get; set; }
        public string PllbGrouping { get; set; }
        public int PllbGroupingLimit { get; set; }
        public int CallCountLimit { get; set; }
        public int CallCountTarget { get; set; }
        public string CallbackHoursBlock { get; set; }
        public string CallbackListCalltime { get; set; }
        public string UserGroup { get; set; }
        public string HopperVlcDupCheck { get; set; }
        public string InGroupDial { get; set; }
        public string InGroupDialSelect { get; set; }
        public string SafeHarborAudioField { get; set; }
        public string PauseAfterNextCall { get; set; }
        public string OwnerPopulate { get; set; }
        public string UseOtherCampaignDnc { get; set; }
        public string AllowEmails { get; set; }
        public string AmdInboundGroup { get; set; }
        public string AmdCallmenu { get; set; }
        public int SurveyWaitSec { get; set; }
        public string ManualDialLeadId { get; set; }
        public string DeadMax { get; set; }
        public string DeadMaxDispo { get; set; }
        public string DispoMax { get; set; }
        public string DispoMaxDispo { get; set; }
        public string PauseMax { get; set; }
        public string MaxInboundCalls { get; set; }
        public string ManualDialSearchCheckbox { get; set; }
        public string HideCallLogInfo { get; set; }
        public string TimerAltSeconds { get; set; }
        public string WrapupBypass { get; set; }
        public string WrapupAfterHotkey { get; set; }
        public string CallbackActiveLimit { get; set; }
        public string CallbackActiveLimitOverride { get; set; }
        public string AllowChats { get; set; }
        public string CommentsAllTabs { get; set; }
        public string CommentsDispoScreen { get; set; }
        public string CommentsCallbackScreen { get; set; }
        public string QcCommentHistory { get; set; }
        public string ShowPreviousCallback { get; set; }
        public string ClearScript { get; set; }
        public string CpdUnknownAction { get; set; }
        public string ManualDialSearchFilter { get; set; }
        public string WebFormAddressThree { get; set; }
        public string ManualDialOverrideField { get; set; }
        public string StatusDisplayIngroup { get; set; }
        public int CustomerGoneSeconds { get; set; }
        public string AgentDisplayFields { get; set; }
        public string AmMessageWildcards { get; set; }
        public string ManualDialTimeout { get; set; }
        public string RoutingInitiatedRecordings { get; set; }
        public string ManualDialHopperCheck { get; set; }
        public string CallbackUseronlyMoveMinutes { get; set; }
        public string OfcomUkDropCalc { get; set; }
        public string ManualAutoNext { get; set; }
        public string ManualAutoShow { get; set; }
        public string AllowRequiredFields { get; set; }
        public string DeadToDispo { get; set; }
        public string AgentXferValidation { get; set; }
        public string ReadyMaxLogout { get; set; }
        public string CallbackDisplayDays { get; set; }
        public string ThreeWayRecordStop { get; set; }
        public string HangupXferRecordStart { get; set; }
        public string ScheduledCallbacksEmailAlert { get; set; }
        public string MaxInboundCallsOutcome { get; set; }
        public string ManualAutoNextOptions { get; set; }
        public string AgentScreenTimeDisplay { get; set; }
        public string NextDialMyCallbacks { get; set; }
        public string InboundNoAgentsNoDialContainer { get; set; }
        public string InboundNoAgentsNoDialThreshold { get; set; }
        public string CidGroupId { get; set; }
        public string PauseMaxDispo { get; set; }
        public string ScriptTopDispo { get; set; }
        public string DeadTriggerSeconds { get; set; }
        public string DeadTriggerAction { get; set; }
        public string DeadTriggerRepeat { get; set; }
        public string DeadTriggerFilename { get; set; }
        public string DeadTriggerUrl { get; set; }
        public string ScheduledCallbacksForceDial { get; set; }
        public string ScheduledCallbacksAutoReschedule { get; set; }
        public string ScheduledCallbacksTimezonesContainer { get; set; }
        public string ThreeWayVolumeButtons { get; set; }
        public string CallbackDnc { get; set; }
        public string ManualDialValidation { get; set; }
        public string MuteRecordings { get; set; }
        public string AutoActiveListNew { get; set; }
        public string CallQuotaLeadRanking { get; set; }
        public string CallQuotaProcessRunning { get; set; }
        public string CallQuotaLastRunDate { get; set; }
        public string SipEventLogging { get; set; }
        public string CampaignScriptTwo { get; set; }
        public string LeaveVmNoDispo { get; set; }
        public string LeaveVmMessageGroupId { get; set; }
        public string DialTimeoutLeadContainer { get; set; }
        public string AmdType { get; set; }
        public string VmmDailyLimit { get; set; }
        public string OpensipsCidName { get; set; }
        public string AmdAgentRouteOptions { get; set; }
        public string BrowserAlertSound { get; set; }
        public int BrowserAlertVolume { get; set; }
        public string ThreeWayRecordStopException { get; set; }
        public string PauseMaxExceptions { get; set; }
        public string HopperDropRunTrigger { get; set; }
        public string DailyCallCountLimit { get; set; }
        public string DailyLimitManual { get; set; }
        public string TransferButtonLaunch { get; set; }
        public int SharedDialRank { get; set; }
        public string AgentSearchMethod { get; set; }
        public string QcScorecardId { get; set; }
        public string QcStatusesId { get; set; }
        public string ClearForm { get; set; }
        public string Leave3wayStartRecording { get; set; }
        public string Leave3wayStartRecordingException { get; set; }
        public string CallsWaitingVlOne { get; set; }
        public string CallsWaitingVlTwo { get; set; }
        public string CallsInqueueCountOne { get; set; }
        public string CallsInqueueCountTwo { get; set; }
        public string InManDialNextReadySeconds { get; set; }
        public string InManDialNextReadySecondsOverride { get; set; }
        public string TransferNoDispo { get; set; }
        public string CallLimit24hourMethod { get; set; }
        public string CallLimit24hourScope { get; set; }
        public string CallLimit24hour { get; set; }
        public string CallLimit24hourOverride { get; set; }
        public string CidGroupIdTwo { get; set; }
    }
}
